"bắc".a = 'north'
"bắc".i = "1.20|0✓|0d|2023-01-03T01:12:43.987362Z"

["Ly6UZFwWb3_qjBEZrnJcJ"]
q = "Summary of The Life You Can Save"
a = "People have a moral obligation to donate as much as they can to prevent suffering and death from extreme poverty"
i = "1.20|0✓|0d|2023-01-03T01:12:57.351074Z"

["G6dPaPnNmr8nh8_ynoBiG"]
q = "Summary of The Life You Can Save"
a = "People have a moral obligation to donate as much as they can to prevent suffering and death from extreme poverty"
i = "1.20|0✓|0d|2023-01-03T01:12:57.35222Z"

["II5uzEL1iap-VAsKbBPuK"]
q = "Summary of The Life You Can Save"
a = "People have a moral obligation to donate as much as they can to prevent suffering and death from extreme poverty"
i = "1.20|0✓|0d|2023-01-03T01:12:57.353361Z"

["jF3G0h0zlnHVbhZ0kUUWw"]
q = "Summary of The Life You Can Save"
a = "People have a moral obligation to donate as much as they can to prevent suffering and death from extreme poverty"
i = "1.20|0✓|0d|2023-01-03T01:12:57.3545Z"

["HnlkG7tFbTU5wsiO9pVk0"]
q = "Summary of The Life You Can Save"
a = "People have a moral obligation to donate as much as they can to prevent suffering and death from extreme poverty"
i = "1.20|0✓|0d|2023-01-03T01:12:57.35564Z"
