"bắc".a = 'north'
"bắc".i = "1.40|6✓|91d|2023-02-11T12:34:19Z"

["iulaK2vF38k_lxwSOSAhF"]
q = "Summary of The Life You Can Save"
a = "People have a moral obligation to donate as much as they can to prevent suffering and death from extreme poverty"
i = "1.30|1✓|1d|2022-12-31T02:54:41.485952Z"

["G6dPaPnNmr8nh8_ynoBiG"]
q = "Summary of The Life You Can Save"
a = "People have a moral obligation to donate as much as they can to prevent suffering and death from extreme poverty"
i = "1.30|1✓|1d|2022-12-31T02:54:41.485952Z"

["II5uzEL1iap-VAsKbBPuK"]
q = "Summary of The Life You Can Save"
a = "People have a moral obligation to donate as much as they can to prevent suffering and death from extreme poverty"
i = "1.30|1✓|1d|2022-12-31T02:54:41.485952Z"

["jF3G0h0zlnHVbhZ0kUUWw"]
q = "Summary of The Life You Can Save"
a = "People have a moral obligation to donate as much as they can to prevent suffering and death from extreme poverty"
i = "1.30|1✓|1d|2022-12-31T02:54:41.485952Z"

["HnlkG7tFbTU5wsiO9pVk0"]
q = "Summary of The Life You Can Save"
a = "People have a moral obligation to donate as much as they can to prevent suffering and death from extreme poverty"
i = "1.30|1✓|1d|2022-12-31T02:54:41.485952Z"
